### ISSUE TITLE
Extract features and evaluation parameters with OpenCV in PolyLaneNet

### ISSUE THREAD

**Issue by juuwong** [yutaekoh/LaneLineDetection#9]

**Comment by juuwong** [comment]
Brainstorm:
- extract basic evaluation parameters provided by TuSimple dataset
- implement confusion matrix to visualize false negative and false positive rates
- comparison between road conditions with TuSimple dataset (ie. sunny/cloudy; straight, curved; road construction; lane patterns)
- note potential areas of improvement based on this data

**Comment by juuwong** [comment]
Unable to generate full video yet. Researching how to generate .pkl predictions file to run gen_video.py file in PolyLaneNet

PolyLaneNet/utils/gen_video.py /
line 12
parser.add_argument("--pred", help=".pkl file to load predictions from")

No .pkl file is generated after testing the model yet.

**Comment by juuwong** [comment]
Encountered an issue with gen_video.py
(base) root@462edb4c0a0b:/workspace# python gen_video.py --pred experiments/tusimple/models/model_2695.pt --cfg cfgs/modified_atlas_tusimple_fulltrain.yaml
total annos 2782
Transforming annotations...
Done.
Using resolution 640x360
Traceback (most recent call last):
  File "gen_video.py", line 67, in <module>
    main()
  File "gen_video.py", line 46, in main
    for idx, pred in tqdm(zip(range(len(dataset)), predictions), total=len(dataset)):
TypeError: 'int' object is not iterable

**Comment by juuwong** [comment]
> Unable to generate full video yet. Researching how to generate .pkl predictions file to run gen_video.py file in PolyLaneNet
> 
> PolyLaneNet/utils/gen_video.py /
> line 12
> parser.add_argument("--pred", help=".pkl file to load predictions from")
> 
> No .pkl file is generated after testing the model yet.

The .pkl file can be substituted with the pretrained model file (model_2695.pt)

**Comment by juuwong** [comment]
> Brainstorm:
> 
> * extract basic evaluation parameters provided by TuSimple dataset
> * implement confusion matrix to visualize false negative and false positive rates
> * comparison between road conditions with TuSimple dataset (ie. sunny/cloudy; straight, curved; road construction; lane patterns)
> * note potential areas of improvement based on this data

Unable to connect to X server issue to complicated to resolve when running from docker container over SSH. Will attempt running gen_video.py to output a video file of predictions
